services:
  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    container_name: fastapi-server
    ports:
      - "8000:8000"
    # 코드 저장소
    volumes:
      - ./fastapi/app:/app
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    runtime: nvidia
    networks:
      - app_network
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    
  ollama:
    build:
      context: ./ollama
      dockerfile: Dockerfile
    container_name: ollama-server
    ports:
      - "11434:11434"
    # 모델 저장소
    volumes:
      - ./ollama/models:/data/models
    networks:
      - app_network
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    command: ollama serve


  chromadb:
    build:
      context: ./chromadb
      dockerfile: Dockerfile
    container_name: chromadb-server
    ports:
      - "8001:8001"
    # 데이터 저장소
    volumes:
      - ./chromadb/data:/chroma/chroma/
    networks:
      - app_network
    # chromadb 포트 변경 8000 -> 8001
    command: uvicorn chromadb.app:app --host 0.0.0.0 --port 8001

networks:
  app_network:
    driver: bridge
